globalFilters:
  #- Cors=allowOrigin:localhost
  #  - KuipAuth=optional
routes:
  - id: crud-user
    uri: http://localhost:9992/ping
    order: 1000
    predicates:
      - Method=POST,GET
      - Host=ioa.letsgo.tech
      - Path=/users/:userId/:type
    filters:
      - RequestSize=10000
      - Cache=100

  - id: crud-blog
    uri: http://blog-backend.letsgo.tech
    order: 100
    predicates:
      - Host=blog.letsgo.tech
      - Path=/blog
      - Method=POST,GET
    filters:
      - RequestSize=10000

  - id: breaker
    uri: http://localhost:9992/ping
    order: 10000
    predicates:
      - Path=/breaker
      - KuipAuth=./kuipAuth.key
    filters:
      - Breaker=

  - id: rateLimit
    uri: http://localhost:9992/ping
    order: 10000
    predicates:
      - Path=/rateLimit
    filters:
      - RateLimit=burst:5,limit:10

  - id: retry
    uri: http://127.0.0.1:8888
    rder: 10000
    predicates:
      - Path=/retry
    filters:
      - Retry=5

  - id: lb
    uri: lb://blog
    order: 10000
    predicates:
      - Path=/lb

  - id: plugin
    uri: http://test
    order: 10000
    predicates:
      - Path=/plugin
    filters:
      #- KuipAuth=necessary

  - id: test
    uri: http://localhost:11112
    order: 10000
    predicates:
      - Path=/test
    filters:
      - SetPath=/ping
